apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: rapid
  namespace: helsearbeidsgiver
  labels:
    team: helsearbeidsgiver
  annotations:
    dcat.data.nav.no/title: "Inntektsmelding rapid"
    dcat.data.nav.no/description: "Mottak og behandling av inntektsmeldinger"
    dcat.data.nav.no/keyword: "sykepenger, inntektsmelding"
    dcat.data.nav.no/theme: "sykepenger"

spec:
  pool: nav-dev
  config:  # optional; all fields are optional too; defaults shown
    minimumInSyncReplicas: 1
    partitions: 10
    replication: 2  # see min/max requirements
    retentionBytes: -1  # -1 means unlimited
    retentionHours: 168  # -1 means unlimited
  acl:
    - team: helsearbeidsgiver
      application: im-aapenimservice
      access: readwrite
    - team: helsearbeidsgiver
      application: im-altinn
      access: readwrite
    - team: helsearbeidsgiver
      application: im-api
      access: readwrite
    - team: helsearbeidsgiver
      application: im-brreg
      access: readwrite
    - team: helsearbeidsgiver
      application: im-joark
      access: readwrite
    - team: helsearbeidsgiver
      application: im-pdl
      access: readwrite
    - team: helsearbeidsgiver
      application: im-inntekt
      access: readwrite
    - team: helsearbeidsgiver
      application: im-inntektservice
      access: readwrite
    - team: helsearbeidsgiver
      application: im-aareg
      access: readwrite
    - team: helsearbeidsgiver
      application: im-helsebro
      access: readwrite
    - team: helsearbeidsgiver
      application: im-forespoersel-besvart
      access: readwrite
    - team: helsearbeidsgiver
      application: im-forespoersel-marker-besvart
      access: readwrite
    - team: helsearbeidsgiver
      application: im-forespoersel-mottatt
      access: readwrite
    - team: helsearbeidsgiver
      application: im-notifikasjon
      access: readwrite
    - team: helsearbeidsgiver
      application: im-db
      access: readwrite
    - team: helsearbeidsgiver
      application: im-distribusjon
      access: readwrite
    - team: helsearbeidsgiver
      application: im-innsending
      access: readwrite
    - team: helsearbeidsgiver
      application: im-tilgangservice
      access: readwrite
    - team: helsearbeidsgiver
      application: im-trengerservice
      access: readwrite
    - team: helsearbeidsgiver
      application: im-bro-spinn
      access: readwrite
    - team: helsearbeidsgiver
      application: im-aktiveorgnrservice
      access: readwrite
    - team: helsearbeidsgiver
      application: im-feil-behandler
      access: readwrite
