apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: inntektsmelding
  namespace: helsearbeidsgiver
  labels:
    team: helsearbeidsgiver
  annotations:
    dcat.data.nav.no/title: "Inntektsmeldinger"
    dcat.data.nav.no/description: "Inntektsmeldinger som blir registrert på nav.no"
    dcat.data.nav.no/keyword: "sykepenger, inntektsmelding"
    dcat.data.nav.no/theme: "sykepenger"

spec:
  pool: nav-dev
  config:  # optional; all fields are optional too; defaults shown
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 2  # see min/max requirements
    retentionBytes: -1  # -1 means unlimited
    retentionHours: 168  # -1 means unlimited
  acl:
    - team: helsearbeidsgiver
      application: im-distribusjon
      access: readwrite
    - team: helsearbeidsgiver
      application: syfoinntektsmelding
      access: read
