apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: privat-sykepenger-inntektsmelding
  namespace: helsearbeidsgiver
  labels:
    team: helsearbeidsgiver
  annotations:
    dcat.data.nav.no/title: "Inntektsmeldinger fra spinosaurus"
    dcat.data.nav.no/description: "Inntektsmeldinger som omhandler sykepenger"
    dcat.data.nav.no/keyword: "sykepenger, inntektsmelding"
    dcat.data.nav.no/theme: "sykepenger"

spec:
  pool: nav-dev
  config:  # optional; all fields are optional too; defaults shown
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 2  # see min/max requirements
    retentionBytes: -1  # -1 means unlimited
    retentionHours: 168  # -1 means unlimited
  acl:
    - team: helsearbeidsgiver
      application: spinosaurus
      access: readwrite
    - team: tbd
      application: spedisjon
      access: read
    - team: tbd
      application: spedisjon-async
      access: read
    - team: flex
      application: flex-syketilfelle
      access: read
    - team: flex
      application: ditt-sykefravaer-backend
      access: read
    - team: flex
      application: flex-inntektsmelding-status
      access: read
