apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: inntektsmelding-bruker
  namespace: helsearbeidsgiver
  labels:
    team: helsearbeidsgiver
  annotations:
    dcat.data.nav.no/title: "Inntektsmeldinger som skal vises til bruker"
    dcat.data.nav.no/description: "Inntektsmeldinger som omhandler sykepenger og skal vises til bruker"
    dcat.data.nav.no/keyword: "sykepenger, inntektsmelding"
    dcat.data.nav.no/theme: "sykepenger"

spec:
  pool: nav-prod
  config: # optional; all fields are optional too; defaults shown
    minimumInSyncReplicas: 1
    partitions: 3
    replication: 2  # see min/max requirements
    retentionBytes: -1  # -1 means unlimited
    retentionHours: 4380  # -1 means unlimited
  acl:
    - team: helsearbeidsgiver
      application: spinosaurus
      access: write   # read, write, readwrite
    - team: flex
      application: flex-syketilfelle
      access: read
    - team: flex
      application: ditt-sykefravaer-backend
      access: read
    - team: flex
      application: flex-inntektsmelding-status
      access: read